name: Build and Push to Docker Hub

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Gotenberg Image
    uses: getlago/lago/.github/workflows/docker-build-multi-arch.yaml@main
    with:
      image-name: ghcr.io/getlago/gotenberg
      registry: ghcr
